# Generated by Django 4.0 on 2021-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='u_question',
            new_name='question',
        ),
    ]
