# Generated by Django 4.0 on 2021-12-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0002_rename_u_question_useranswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
    ]
