# Generated by Django 4.0 on 2021-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0003_remove_useranswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
