# Generated by Django 4.0 on 2021-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0004_useranswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
